#!/bin/bash

# Ejecuta una serie de tareas previas a un git commit.
# Use el argumento --no-verify para evitarlo de forma puntual.

echo "Ejecutando pre-commit"
CUR_DIR="$(pwd)"
cd ./code/tools

./run_tests.sh
if [ $? -ne 0 ]; then
	echo "Los tests deben pasar correctamente"
	exit 1
fi

./auto_format.sh
./generate_docs.sh 2>/dev/null

cd $CUR_DIR
git add .
git add -u .
