#!/bin/bash

# Ejecuta una serie de tareas previas a un git commit.
# Use el argumento --no-verify para evitarlo de forma puntual.

echo "Ejecutando pre-commit"
cd ./code/tools

./run_tests.sh
if [ $? -ne 0 ]; then
	echo "Los tests deben pasar correctamente"
	exit 1
fi
